# Generated by Django 5.2.7 on 2026-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('external_driver', 'External Driver'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
