# Generated by Django 5.2.7 on 2026-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sosevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_address_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(default='car', max_length=20),
        ),
    ]
