# Generated by Django 5.2.7 on 2026-06-07 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ridelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('day_of_week', models.CharField(max_length=20)),
                ('class_start_time', models.TimeField()),
                ('class_end_time', models.TimeField()),
                ('dropoff_name', models.CharField(max_length=200)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('pickup_name', models.CharField(max_length=200)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('preferred_departure_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
