# Generated by Django 5.2.7 on 2026-06-07 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=500)),
                ('day_of_week', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=50)),
                ('demand_level', models.CharField(max_length=20)),
                ('predicted_rides', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.IntegerField(blank=True, null=True)),
                ('route', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('departure_time', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField(default=0.0)),
                ('duration', models.FloatField(default=0.0)),
                ('shared_seats', models.IntegerField(default=0)),
                ('estimated_co2_saved', models.FloatField(default=0.0)),
                ('estimated_money_saved', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CopilotInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('insight_type', models.CharField(max_length=50)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('label', models.CharField(max_length=50)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_safety_scores', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_safety_scores', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ride')),
            ],
        ),
    ]
